package dev.tracedown.monolith

import io.ktor.http.ContentType
import io.ktor.server.application.Application
import io.ktor.server.http.content.singlePageApplication
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import org.slf4j.LoggerFactory

/**
 * Serves the bundled frontend from the classpath, appended to the gateway's
 * module list so the SPA and the API share one origin (`/api/v1` is native).
 *
 * `/config.js` is generated here rather than served from the bundle: the
 * WebSocket endpoint lives on the realtime port, and the agents UI is switched
 * off — the monolith executes probes in-process, so there are no agents to
 * manage and the connect-agent flow would be a trap.
 */
@Suppress("unused") // referenced from ktor.application.modules via config
fun Application.monolithFrontend() {
    val log = LoggerFactory.getLogger("dev.tracedown.monolith.Frontend")
    val realtimePort = System.getenv("REALTIME_PORT")?.toIntOrNull() ?: 20870
    // Default: the browser dials the realtime port directly, which works when
    // that port is reachable (plain-HTTP setups). Behind a TLS-terminating
    // proxy set WS_URL — e.g. "/ws", proxied to the realtime port — so the
    // WebSocket rides the same origin as the page.
    val wsUrl = System.getenv("WS_URL")?.takeIf { it.isNotBlank() }
    val wsExpr = if (wsUrl != null) {
        "\"$wsUrl\""
    } else {
        "(location.protocol === \"https:\" ? \"wss\" : \"ws\") + \"://\" + location.hostname + \":$realtimePort/ws\""
    }
    val bundled = javaClass.classLoader.getResource("frontend/index.html") != null

    routing {
        get("/config.js") {
            call.respondText(
                """
                // Generated by the Tracedown monolith.
                window.__TRACEDOWN_ENV__ = {
                  wsUrl: $wsExpr,
                  features: { agents: false },
                };
                """.trimIndent(),
                ContentType.Text.JavaScript,
            )
        }
        if (bundled) {
            singlePageApplication {
                useResources = true
                filesPath = "frontend"
                defaultPage = "index.html"
            }
        } else {
            get("/") {
                call.respondText(
                    "Tracedown monolith is running, but no frontend bundle is baked into this jar. " +
                        "Build with -PmonolithFrontend=latest, or serve the frontend separately.",
                    ContentType.Text.Plain,
                )
            }
        }
    }
    if (bundled) log.info("serving bundled frontend (agents UI disabled, ws on port {})", realtimePort)
    else log.warn("no frontend bundle in this jar — / serves a plain notice")
}
